<?php

namespace AppBundle\Repository;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends \Doctrine\ORM\EntityRepository
{
    public function countTickets(\DateTime $date)
    {
        $qb=$this->createQueryBuilder('o')
            ->select('SUM(o.number)')
            ->where ('o.date = :date')
            ->setParameter('date',$date);
        return $qb->getQuery()->getSingleScalarResult();
    }
}
